version: '3.8'

services:
  investment-bot:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ADMIN_BOT_TOKEN=${ADMIN_BOT_TOKEN}
      - USER_BOT_TOKEN=${USER_BOT_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/investment_bot
      - BTC_ADDRESS=${BTC_ADDRESS}
      - USDT_TRC20_ADDRESS=${USDT_TRC20_ADDRESS}
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=investment_bot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
